### ISSUE TITLE
why you have kept, NOSCAN=1?

### ISSUE THREAD

**Issue by ajaymalikbol** [srcclr/agent-docker#1]
curl -sSL https://download.sourceclear.com/ci.sh | CACHE_DIR=/tmp NOSCAN=1 bash

by default value of NOSCAN=0, why you have kept it 1

**Comment by dariusf** [comment]
We do that in the Dockerfile just for the side effect of installing the agent. It only runs later, when a container is created.

**Comment by jsyeo** [comment]
Closing because not a bug or an issue.
